"""18 default legal/regulatory documents used to seed the RAG knowledge base.

Direct port of DEFAULT_DOCUMENTS from the original src/default_documents.ts.
"""

DEFAULT_DOCUMENTS = [
    {
        "id": "doc_1",
        "code": "Luật PCCC",
        "title": "Luật Phòng cháy, chữa cháy và Cứu nạn, cứu hộ",
        "type": "LUẬT",
        "link": "#",
        "content": "Quy định chung về nguyên tắc, trách nhiệm, hoạt động phòng cháy, chữa cháy và cứu nạn, cứu hộ.\n- Điều 20 quy định về trách nhiệm của chủ đầu tư, chủ hộ gia đình trong việc tự bảo đảm an toàn PCCC.\n- Quy định việc thiết kế, thẩm duyệt, nghiệm thu về PCCC đối với công trình xây dựng.",
        "isCustom": False,
    },
    {
        "id": "doc_2",
        "code": "NĐ105/2025/NĐ-CP",
        "title": "Nghị định - Quy định chi tiết một số điều và biện pháp thi hành Luật PCCC và CNCH",
        "type": "Nghị định",
        "link": "#",
        "content": "Nghị định quy định chi tiết về quản lý nhà nước, thẩm duyệt thiết kế, nghiệm thu và kiểm tra an toàn PCCC.\n- Phụ lục I: Danh mục cơ sở thuộc diện quản lý về PCCC (nhà ở kết hợp kinh doanh phải khai báo).\n- Phụ lục III: Danh mục dự án, công trình thuộc diện thẩm duyệt thiết kế về PCCC của cơ quan Cảnh sát PCCC.\n- Đối với Nhà hỗn hợp, nhà ở riêng lẻ kết hợp kinh doanh dịch vụ thương mại: bắt buộc thẩm duyệt khi công trình \"cao từ 7 tầng trở lên HOẶC tổng diện tích sàn xây dựng từ 3.000 m² trở lên\". \n- Riêng mục 1 (nhà ở): thẩm duyệt khi \"cao từ 7 tầng trở lên HOẶC tổng diện tích sàn xây dựng từ 3.000 m² trở lên\".\n- Nếu không thuộc đối tượng thẩm duyệt, chủ đầu tư tự chịu trách nhiệm bảo đảm an toàn PCCC, thể hiện thiết kế trong hồ sơ phục vụ kiểm tra 3 năm/lần bởi UBND cấp xã/phường.",
        "isCustom": False,
    },
    {
        "id": "doc_3",
        "code": "147/2020/TT-BCA",
        "title": "Thông tư - Quy định biện pháp bảo đảm an toàn PCCC và CNCH đối với cơ sở kinh doanh dịch vụ Karaoke",
        "type": "Thông tư",
        "link": "#",
        "content": "Quy định các tiêu chuẩn kỹ thuật an toàn PCCC tối thiểu đối với cơ sở kinh doanh dịch vụ Karaoke và vũ trường.\n- Bố trí tối thiểu 02 lối thoát nạn độc lập.\n- Thiết kế hệ thống báo cháy tự động, hệ thống chữa cháy tự động (sprinkler) không phụ thuộc quy mô diện tích.\n- Kết cấu ngăn cháy lan và sử dụng vật liệu hoàn thiện không cháy hoặc khó cháy.",
        "isCustom": False,
    },
    {
        "id": "doc_4",
        "code": "QCVN 01:2020/BCT",
        "title": "Quy chuẩn kỹ thuật Quốc gia về Yêu cầu Thiết kế Cửa hàng Xăng dầu",
        "type": "QCVN",
        "link": "#",
        "content": "Quy chuẩn kỹ thuật bắt buộc áp dụng khi xây dựng, cải tạo cửa hàng xăng dầu trên mặt đất hoặc mặt nước.\n- Khoảng cách an toàn từ cột bơm, bể chứa đến các công trình công cộng, nhà dân lân cận.\n- Trang bị phương tiện chữa cháy xách tay, hệ thống nối đất chống tĩnh điện và hệ thống thu hồi hơi xăng dầu.",
        "isCustom": False,
    },
    {
        "id": "doc_5",
        "code": "QCVN 02:2020/BCA",
        "title": "Quy chuẩn kỹ thuật Quốc gia về Trạm bơm nước Chữa cháy",
        "type": "QCVN",
        "link": "#",
        "content": "Quy định yêu cầu thiết kế, lắp đặt trạm bơm nước chữa cháy trong các nhà và công trình.\n- Trạm bơm chữa cháy phải đặt trong phòng ngăn cháy riêng biệt, có cửa mở trực tiếp ra ngoài hoặc hành lang thoát nạn.\n- Bố trí máy bơm động cơ dự phòng độc lập, nguồn điện ưu tiên hoặc máy phát điện độc lập.",
        "isCustom": False,
    },
    {
        "id": "doc_6",
        "code": "QCVN 06:2022/BXD (Sửa đổi 01-2023)",
        "title": "Quy chuẩn kỹ thuật Quốc gia về An toàn Cháy cho Nhà và Công trình",
        "type": "QCVN",
        "link": "#",
        "content": "Quy chuẩn cốt lõi điều chỉnh toàn bộ giải pháp an toàn cháy, bậc chịu lửa, khoảng cách an toàn và thoát nạn.\n- Phân nhóm nguy hiểm cháy theo công năng: F1.4 là nhà ở riêng lẻ, nhà ở riêng lẻ kết hợp mục đích khác (nhà hỗn hợp).\n- Bậc chịu lửa tối thiểu: Bảng H.1 Phụ lục H quy định bậc chịu lửa tối thiểu cần thiết dựa trên nhóm công năng, số tầng và chiều cao. Với nhà nhóm F1.4 cao đến 4 tầng, cho phép Bậc chịu lửa III. Bậc III yêu cầu giới hạn chịu lửa tối thiểu: Cột R45, Dầm R45, Sàn REI45, Tường chịu lực REI45.\n- Ngăn cháy lan: Tường ngăn cháy giữa khu kinh doanh (tầng 1) và khu nhà ở (tầng 2-4) phải đạt tối thiểu REI 45 hoặc vách ngăn cháy bậc 1 (EI 45). Cửa thông phải là cửa chống cháy EI 30 tự đóng.\n- Khoảng cách an toàn PCCC giữa các nhà (Mục 4, Bảng 2): Khoảng cách tối thiểu từ công trình bậc III đến nhà bậc III khác là >= 8m (có thể giảm xuống >= 6m nếu tường đối diện là tường đặc không cháy REI 45). Khoảng cách đến công trình bậc IV/V là >= 10m. Khoảng cách ranh giới lô đất >= 3m (nếu không có lỗ mở) và >= 6m (nếu có cửa sổ). Nhà phố tiếp giáp liền kề khoảng cách = 0 khi tường chung là tường ngăn cháy REI 45 đặc.\n- Giải pháp thoát nạn (Phần 6 & Phụ lục A.2):\n  + Số lối ra thoát nạn: Tối thiểu 1 lối cho mỗi tầng đối với nhà dưới 4 tầng, chiều cao <= 12m, nhóm F1.4. Khuyến nghị bố trí 2 lối.\n  + Cửa thoát tầng 1: mở ra ngoài công trình, chiều rộng thông thủy >= 0.9m.\n  + Thang bộ: Thang bộ loại 2 (hở, trong nhà) hoặc loại 3 (hở, ngoài nhà) được phép cho nhà có chiều cao PCCC <= 9m. Chiều rộng thông thủy thang >= 1.05m, chiếu nghỉ >= chiều rộng thang.\n  + Khoảng cách di chuyển tối đa: <= 40m (hành lang một phía); <= 25m (hành lang cụt).\n  + Chiều cao thông thủy đường thoát nạn >= 2.0m, cửa thoát >= 1.9m. Hành lang rộng >= 1.0m.\n  + Cấm bố trí kho hạng A, B, C tại tầng thoát nạn trực tiếp ra ngoài.",
        "isCustom": False,
    },
    {
        "id": "doc_7",
        "code": "QCVN 10:2025/BCA",
        "title": "Quy chuẩn kỹ thuật Quốc gia về Trang bị, bố trí phương tiện PCCC CNCH cho Nhà và Công trình",
        "type": "QCVN",
        "link": "#",
        "content": "Quy chuẩn mới nhất thay thế các quy chuẩn cũ quy định việc trang bị hệ thống báo cháy, chữa cháy, bình chữa cháy, đèn chiếu sáng sự cố và cấp nước.\n- Hệ thống báo cháy tự động: Bắt buộc trang bị cho nhà hỗn hợp, nhà ở kết hợp kinh doanh khi cao từ 7 tầng trở lên (Phụ lục A, mục 1a).\n- Thiết bị báo cháy độc lập (smoke detector): Cho phép thay thế hệ thống báo cháy tự động cho nhà ở kết hợp kinh doanh dưới 7 tầng. Khuyến nghị lắp đặt tối thiểu 1 thiết bị/phòng ngủ và 1 thiết bị/tầng tại hành lang, liên động âm thanh với nhau.\n- Hệ thống chữa cháy tự động (sprinkler): Thường bắt buộc cho nhà ở kết hợp kinh doanh dịch vụ khi chiều cao PCCC >= 30m (Bảng A.1 - QCVN 10:2025). Khách sạn, nhà nghỉ, trung tâm thương mại quy mô lớn cũng bắt buộc tùy quy mô diện tích.\n- Hệ thống họng nước chữa cháy trong nhà: Bắt buộc cho nhà dắt tay, nhà công cộng thương mại. Theo Bảng H.5: nhà công cộng <= 12m chiều cao, có khối tích <= 5.000 m³ yêu cầu tối thiểu 1 tia phun nước đồng thời, lưu lượng >= 2.5 L/s. Khuyến nghị lắp họng DN50 tại mỗi tầng.\n- Bình chữa cháy xách tay: Bắt buộc cho toàn bộ công trình, mọi loại hình (Điều 2.6). Tiêu chuẩn: lắp đặt bình bột ABC >= 4kg hoặc CO2 >= 3kg. Tối thiểu 1 bình/tầng, bố trí tại lối đi, cầu thang hoặc hành lang. Bán kính bảo vệ <= 25m/bình. Tầng 1 (kd) tối thiểu 2 bình do nguy cơ cao.\n- Đèn chiếu sáng sự cố và chỉ dẫn thoát nạn (đèn EXIT): Bắt buộc bố trí dọc đường và lối ra thoát nạn, cầu thang bộ. Nguồn điện dự phòng tự động hoạt động tối thiểu 2 giờ, độ rọi trung bình >= 1 lux.",
        "isCustom": False,
    },
    {
        "id": "doc_8",
        "code": "QCVN 13:2018/BXD",
        "title": "Quy chuẩn kỹ thuật Quốc gia về Gara Ô-tô",
        "type": "QCVN",
        "link": "#",
        "content": "Quy chuẩn quy định yêu cầu thiết kế và bố trí gara để xe ô tô trong nhà và ngoài trời.\n- Khoảng cách ngăn cháy từ gara đến các công trình lân cận.\n- Giải pháp thông gió, hút khói cưỡng bức khi thiết kế gara tầng hầm hoặc bán hầm.\n- Trang bị hệ thống báo cháy và chữa cháy tự động bằng nước hoặc bọt.",
        "isCustom": False,
    },
    {
        "id": "doc_9",
        "code": "TCVN 2622:1995",
        "title": "Phòng cháy, chống cháy cho Nhà và Công trình - Yêu cầu thiết kế",
        "type": "TCVN",
        "link": "#",
        "content": "Tiêu chuẩn quốc gia về phân cấp công trình xây dựng, bố trí trang thiết bị chữa cháy, tính toán lưu lượng nước chữa cháy ngoài nhà.",
        "isCustom": False,
    },
    {
        "id": "doc_10",
        "code": "TCVN 5687:2024",
        "title": "Thông gió và Điều hòa không khí - Yêu cầu thiết kế",
        "type": "TCVN",
        "link": "#",
        "content": "Tiêu chuẩn quy định thiết kế các hệ thống thông gió, đặc biệt là hệ thống hút khói hành lang, hút khói tầng hầm, và hệ thống tăng áp buồng thang bộ, giếng thang máy khi có cháy.",
        "isCustom": False,
    },
    {
        "id": "doc_11",
        "code": "TCVN 6161:1996",
        "title": "Phòng cháy chữa cháy - Chợ và trung tâm thương mại - Yêu cầu thiết kế",
        "type": "TCVN",
        "link": "#",
        "content": "Tiêu chuẩn quy định các giải pháp quy hoạch, kiến trúc, kết cấu ngăn cháy và trang bị kỹ thuật PCCC đối với các công trình chợ và trung tâm thương mại.",
        "isCustom": False,
    },
    {
        "id": "doc_12",
        "code": "TCVN 7161-9:2009",
        "title": "Hệ thống chữa cháy bằng khí - Tính chất vật lý và thiết kế hệ thống - Phần 9: Khí chữa cháy HFC-227ea",
        "type": "TCVN",
        "link": "#",
        "content": "Quy định quy chuẩn thiết kế hệ thống chữa cháy bằng khí HFC-227ea (FM200) cho các phòng thiết bị điện tử, server máy chủ, thư viện tài liệu quý.",
        "isCustom": False,
    },
    {
        "id": "doc_13",
        "code": "TCVN 7336:2021",
        "title": "Phòng cháy chữa cháy - Hệ thống chữa cháy tự động bằng nước, bọt - Yêu cầu thiết kế và lắp đặt",
        "type": "TCVN",
        "link": "#",
        "content": "Tiêu chuẩn hướng dẫn thiết kế chi tiết hệ thống Sprinkler, Drencher chữa cháy tự động, xác định lưu lượng diện tích bảo vệ và thông số đường ống cấp.",
        "isCustom": False,
    },
    {
        "id": "doc_14",
        "code": "TCVN 7435-1:2004 / TCVN 7435-2:2004",
        "title": "Phòng cháy, chữa cháy - Bình chữa cháy xách tay và xe đẩy chữa cháy- Phần 1 & 2: Lựa chọn, bố trí, kiểm tra, bảo trì",
        "type": "TCVN",
        "link": "#",
        "content": "Tiêu chuẩn quốc gia chi tiết hướng dẫn lựa chọn chủng loại bình phù hợp với loại đám cháy (A, B, C, D, E), kỹ thuật bố trí và kiểm định bảo dưỡng định kỳ tối thiểu 6 tháng/lần.",
        "isCustom": False,
    },
    {
        "id": "doc_15",
        "code": "TCVN 7568-14:2025",
        "title": "Hệ thống báo cháy - Phần 14: Thiết kế, lắp đặt các hệ thống báo cháy cho Nhà và Công trình",
        "type": "TCVN",
        "link": "#",
        "content": "Tiêu chuẩn quốc gia quy định chi tiết kỹ thuật lắp đặt đầu báo khói, đầu báo nhiệt, nút ấn khẩn cấp, tủ trung tâm báo cháy và liên động hệ thống kỹ thuật.",
        "isCustom": False,
    },
    {
        "id": "doc_16",
        "code": "TCVN 9385:2012",
        "title": "Chống sét cho công trình xây dựng - Hướng dẫn thiết kế, kiểm tra và bảo trì hệ thống",
        "type": "TCVN",
        "link": "#",
        "content": "Quy định thiết kế hệ thống kim thu sét, dây thoát sét, bãi tiếp địa thu lôi cho các công trình nhà ở và dân dụng, kiểm tra điện trở nối đất định kỳ hàng năm.",
        "isCustom": False,
    },
    {
        "id": "doc_17",
        "code": "TCVN 13456:2022",
        "title": "Phòng cháy chữa cháy - Phương tiện Chiếu sáng sự cố và Chỉ dẫn thoát nạn - Yêu cầu thiết kế, lắp đặt",
        "type": "TCVN",
        "link": "#",
        "content": "Tiêu chuẩn quy định kỹ thuật lắp đặt đèn EXIT chỉ hướng và đèn sự cố chiếu sáng khẩn cấp, khoảng cách tối đa giữa các đèn dọc lối đi, các tiêu chuẩn độ rọi.",
        "isCustom": False,
    },
    {
        "id": "doc_18",
        "code": "TCVN 14496:2025",
        "title": "Phòng cháy chữa cháy - Hệ thống chữa cháy tự động bằng nước cho nhà kho có chiều cao sắp xếp hàng hóa trên giá đỡ trên 5,5m đến 25m - Yêu cầu thiết kế",
        "type": "TCVN",
        "link": "#",
        "content": "Quy chuẩn thiết kế đầu phun chữa cháy đặc chủng cho khu vực nhà kho kệ cao xếp giá đỡ thông minh.",
        "isCustom": False,
    },
]
